- README.md
- src/SIMD.jl
- test/runtests.jl
This PR adds a shufflevector function, mapping to the LLVM shufflevector instruction. It seems to work but there are a number of design decisions and missing pieces to address, at least including:
* Should the mask be 1-based like Julia usually is or 0-based to match LLVM and low level instruction conventions?
* The one and two operand versions share most of the code but not sure how best to refactor them.
* There are no tests yet. It's not obvious how to relate shufflevector tests to the nbytes parameter in runtests.jl.
* The calling convention with `VAL{}` for the mask is not too pretty, but is there any reasonable way to avoid it?
> Add vector shuffles

- .travis.yml
- REQUIRE
- appveyor.yml
- src/SIMD.jl
- test/runtests.jl
This addresses the most recent deprecations on v0.6.
I was also thinking on updating SIMD.jl to use the new `llvmcall` calling convention to call llvm intrinsics allowing us to cut down on the number of generated LLVM IR snippets.
> deprecations on v0.6

- src/SIMD.jl
This fixes a late Julia 0.7 deprecation and should make SIMD ready for Julia 1.0.
> Fix nextpow2 deprecation.

- .travis.yml
- README.md
- appveyor.yml
- src/SIMD.jl
- test/runtests.jl
This PR
- deprecated any use of `Compat`
- stopped using `@info`
- Refactored into using the `@testset` macro
- had to use `global` for the local scoped `const` declarations so they could be accessed across testsets.
@vchuravy
> Tests cleanup

- README.md
- src/SIMD.jl
- test/runtests.jl
Fixes #35 
As an indication that this is the right choice, this PR found a slow fallback in converting a `Vec` to another element type.
With this PR
```jl
julia> a = Vec{4, Float64}((1.0,2.0,3.0,4.0))
<4 x Float64>[1.0, 2.0, 3.0, 4.0]
julia> f(a) = convert(Vec{4, Float32}, a)
f (generic function with 1 method)
julia> @code_native f(a)
vcvtpd2psy      (%rsi), %xmm0
vmovapd %xmm0, (%rdi)
movq    %rdi, %rax
retq
nopl    (%rax)
;}
```
but previously it was fell back to just iterating to create the Tuple:
```jl
julia> @code_native f(a)
.section        __TEXT,__text,regular,pure_instructions
; Function f {
; Location: REPL[3]:1
pushq   %r14
pushq   %rbx
subq    $40, %rsp
movq    %rdi, %r14
vxorps  %xmm0, %xmm0, %xmm0
vmovaps %xmm0, 16(%rsp)
movq    $0, 32(%rsp)
movabsq $jl_get_ptls_states_fast, …
```
> remove DenseVector subtyping

- README.md
- src/SIMD.jl
- test/runtests.jl
Hi, thanks for implementing this library!
I wanted to play with the gather operation so I implemented it using SIMD.jl infrastructure (whish was surprisingly straightforward).  Do you think it's good to add this?
As a side note, if you want to get fancy, I think indexing `arr[idx]` by a `Vec` can be a sugar for `vgather` (and `arr[idx] = vec` for scatter in the future).
> Add gather

- src/SIMD.jl
Using:
```jl
julia> f(v, i) = @inbounds v[i]
julia> @code_llvm f(Vec((1.0,2.0,3.0,4.0)), 1);
```
Before:
```
%2 = add i64 %1, -1
%3 = icmp ult i64 %2, 4
br i1 %3, label %pass, label %fail
fail:                                             ; preds = %top
%4 = bitcast { <4 x double> } addrspace(11)* %0 to i8 addrspace(11)*
call void @jl_bounds_error_unboxed_int(i8 addrspace(11)* %4, %jl_value_t* inttoptr (i64 4607209856 to %jl_value_t*), i64 %1)
unreachable
pass:                                             ; preds = %top
%5 = getelementptr inbounds { <4 x double> }, { <4 x double> } addrspace(11)* %0, i64 0, i32 0, i64 %2
;}}
%6 = load double, double addrspace(11)* %5, align 8
ret double %6
}
```
:(
After:
```
%2 = add i64 %1, -1
%3 = getelementptr inbounds { <4 x double> }, { <4 x double> } …
```
> propagate inbounds for getindex

- Project.toml
It looks like the UUID in Project.toml is different from the one in the registry: https://github.com/JuliaRegistries/General/blob/master/S/SIMD/Package.toml
This PR make `]test SIMD` works after `]dev SIMD`, although I remember it worked before... Maybe something changed in Pkg.jl?  Anyway, I think it's better to match the UUID.
> Fix Project.toml UUID

- src/SIMD.jl
- test/runtests.jl
This PR addresses the issue @timholy (https://github.com/JuliaArrays/MappedArrays.jl/pull/24#issuecomment-460568978) and @mbauman (https://github.com/eschnett/SIMD.jl/pull/40#discussion_r254131184) pointed out:
> These `getindex` methods cannot be used generally on all `SubArray`s — the use of `pointer` means that they need to at least be `StridedSubArray`s. This will fail for a `view(A, [1,2], [1,2])`, for example. --- https://github.com/eschnett/SIMD.jl/pull/40#discussion_r254131184
I also added support for the case with non-strided axes in the non-first dimensions (e.g., `view(ones(5, 5), :, [1,3])`).
> Make indexing aware of SubArray memory layout

- Project.toml
While InteractiveUtils is used for testing, it is not used within the package itself.
> Remove spurious dependency on InteractiveUtils

- src/LLVM_intrinsics.jl
- src/SIMD.jl
- src/arrayops.jl
- src/simdvec.jl
- test/runtests.jl
This PR adds Masked Vector Expanding Load and Compressing Store Intrinsics: https://llvm.org/docs/LangRef.html#masked-vector-expanding-load-and-compressing-store-intrinsics
I'm not sure how it should be called. I call them `vloadx` and `vstorec` to match(?) with existing names. But I don't mind renaming them to something else.
Example:
```julia
function compress_scalar!(dest, pred, src)
j = firstindex(dest)
@inbounds for i in eachindex(dest, src, pred)
if pred[i]
dest[j] = src[i]
j += 1
end
end
return dest
end
function compress_simd!(dest, pred, src, ::Val{N} = Val(4)) where {N}
@assert axes(dest) == axes(src) == axes(pred)
simd_bound = lastindex(src) - N + 1
i = firstindex(src)
j = firstindex(dest)
lanes = VecRange{N}(0)
@inbounds while i <= simd_bound
mask = pred[lanes + i] …
```
> Add expandload and compressstore

- src/arrayops.jl
Fixes https://github.com/eschnett/SIMD.jl/pull/68#issuecomment-658143620
> Don't pass a tuple of indices when calculating the pointer in an 1D array.

- .travis.yml
- src/LLVM_intrinsics.jl
- src/LLVM_intrinsics_old.jl
- src/SIMD.jl
- test/runtests.jl
Ref https://github.com/JuliaLang/julia/pull/36576, which will be a part of Julia 1.6.
Since I did this development using an Debug+Asserts build of LLVM, this PR includes some additional fixes to get through the entire test suite. Those could be back-ported to the master branch.
> Adapt to upcoming llvmcall rework

- src/arrayops.jl
- test/runtests.jl
It took me forever to look at the library after the rewrite. Nice work, by the way! I just noticed the `vloada` method I used in a project was not defined anymore. This patch re-introduces it.
> Re-defining vloada and vstorea for pointers

- src/arrayops.jl
- test/runtests.jl
I added ReinterpretArrays to the supported contiguous array types. I think it should just work?
> Add ReinterpretArrays to supported array types

- src/arrayops.jl
- test/runtests.jl
Before this PR, gather and scatter didn't work with multi-dimensional arrays:
```julia
julia> x1 = ones(4);
julia> x1[Vec(1, 3)]
<2 x Float64>[1.0, 1.0]
julia> x2 = ones(2, 2);
julia> x2[Vec(1, 3)]
ERROR: MethodError: no method matching vgather(::Vec{2,Ptr{Float64}}, ::Nothing)
Closest candidates are:
vgather(::Vec{N,Ptr{T}}) where {N, T<:Union{Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8}} at /home/takafumi/.julia/dev/SIMD/src/arrayops.jl:149
vgather(::Vec{N,Ptr{T}}, ::Vec{N,Bool}) where {N, T<:Union{Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8}} at /home/takafumi/.julia/dev/SIMD/src/arrayops.jl:149
vgather(::Vec{N,Ptr{T}}, ::Vec{N,Bool}, ::Val{Aligned}) where {N, T<:Union{Float32, Float64, Int16, Int32, Int64, Int8, UInt16, …
```
> Fix gather/scatter with multi-dimensional arrays

- Project.toml
- src/LLVM_intrinsics.jl
- src/LLVM_intrinsics_old.jl
- src/simdvec.jl
- test/runtests.jl
This is in response to issue #82.  I tested it on 1.54 and 1.6.0-rc3 and it all works.  1.0.5 crashed, I think in the "Element-wise access" test set, so I don't think that is anything I've done:
`LLVM ERROR: Cannot select: 0x20be2f0: f64 = <<Unknown DAG Node>> ConstantFP:f64<0.000000e+00>, 0x1f512b0`
But the compat section of the Project.toml just says Julia 1.5 so that is probably fine.
Not sure if you would like more indepth tests for the funnel shifts, like test it with various integer types, or if there are specific bit patterns that are a "good" test.
I'm also not sure if I should have included **both** implementations:
```
Base.bitrotate(x::Vec, k::Vec)
Base.bitrotate(x::Vec{N, T}, k::Integer) where {N, T}
```
Would users of bitrotate and vectors expect to rotate all values by the …
> Fixed the fshl and fshr intrinsics and added bitrotate for Vec objects.

- src/LLVM_intrinsics.jl
I haven't actually tested on LLVM 12.
> LLVM 12 updates.

- Project.toml
- src/LLVM_intrinsics.jl
- src/simdvec.jl
This sould be fair since julia itself uses `@simd` in `sum` and `prod`
Before:
```llvm
julia> using SIMD
julia> dot1(A::Vec{8,Float32},B::Vec{8,Float32}) = sum(A * B)
dot1 (generic function with 1 method)
julia> code_native(dot1, Tuple{Vec{8,Float32}, Vec{8,Float32}})
.section        __TEXT,__text,regular,pure_instructions
; ┌ @ REPL[2]:1 within `dot1`
; │┌ @ simdvec.jl:253 within `*`
; ││┌ @ LLVM_intrinsics.jl:212 within `fmul` @ LLVM_intrinsics.jl:212
; │││┌ @ LLVM_intrinsics.jl:221 within `macro expansion`
vmovups (%rdi), %ymm0
vmulps  (%rsi), %ymm0, %ymm0
vxorps  %xmm1, %xmm1, %xmm1
; │└└└
; │┌ @ simdvec.jl:473 within `sum`
; ││┌ @ simdvec.jl:463 within `reduce`
; │││┌ @ LLVM_intrinsics.jl:806 within `reduce_fadd`
; ││││┌ @ LLVM_intrinsics.jl:821 within `macro expansion`
vaddss …
```
> allow reassociation in fp sum and prod

- src/LLVM_intrinsics.jl
Fixes a test error as shown in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c6440b9_vs_d0156b5/SIMD.primary.log
> fix llvm intrinsic function for pow, powi

- src/simdvec.jl
This prevented some vectorization, since the boundscheck was not elided, even if inlined. I get a 2x performance boost with this.
> Add `@propagate_inbounds` to `getindex`/`setindexi!` on `Vec`

- src/LLVM_intrinsics.jl
- src/simdvec.jl
- test/runtests.jl
Should fix https://github.com/eschnett/SIMD.jl/issues/103
@seelengrab, can you test this?
> add fastmath for min and max

- src/arrayops.jl
> NFC remove deprecated `Vararg{<:Any}`

- src/LLVM_intrinsics.jl
Found as part of JuliaLang/julia#46372 - the reference parser treats triple quoted lines of uneven whitespace in a weird inconsistent way so this is changed in the new parser. This change removes the uneven whitespace.
> Fix uneven trailing whitespace in strings

- src/simdvec.jl
- test/runtests.jl
…ehavior)
Due to an off by one, shifting with the exact amount as the number of bits caused garbage to get returned:
```
julia> f2(v) = v >> 64
f2 (generic function with 1 method)
julia> v = Vec(1,2,3,4)
<4 x Int64>[1, 2, 3, 4]
julia> @code_llvm f2(v)
;  @ REPL[25]:1 within `f2`
define void @julia_f2_542([1 x <4 x i64>]* noalias nocapture noundef nonnull sret([1 x <4 x i64>]) align 32 dereferenceable(32) %0, [1 x <4 x i64>]* nocapture noundef nonnull readonly align 16 dereferenceable(32) %1) #0 {
top:
ret void
}
```
Ref https://discourse.julialang.org/t/simd-struggles-seeking-solutions-with-kangarootwelve-jl/105800/23?u=kristoffer.carlsson
> fix some shift operations to agree with Base (and prevent undefined behavior)

- test/runtests.jl
The IR is `fmul fast <4 x double> %\"v::Vec.unbox\", splat (double 2.000000e+00)` on llvm 20.
> Update test for LLVM 20

- .github/workflows/ci.yml
- .github/workflows/ci_julia_nightly.yml
- README.md
- src/LLVM_intrinsics.jl
- src/SIMD.jl
- src/arrayops.jl
- src/simdvec.jl
- test/Project.toml
- test/opencl.jl
- test/runtests.jl
and add some OpenCL tests. The gather/scatter tests will require a small
upstream change to allow disabling SPIRV validation, since the validator
doesn't seem to understand the `SPV_INTEL_masked_gather_scatter`
extension.
addresses https://github.com/eschnett/SIMD.jl/issues/80
written with help from Copilot
> add support for LLVMPtr
